### ISSUE TITLE
Bots telling me its an online server, but it's not.

### ISSUE THREAD

**Issue by akisha009** [PureGero/minecraft-stress-test#17]
Bot5 (957bd75a-2799-3660-aa34-d1833e9c00b3) has logged in on an ONLINEMODE server, stopping
Bot5 has disconnected from serverip:26465

**Comment by PureGero** [comment]
What server version are you running? Are there any proxies?

**Comment by akisha009** [comment]
Yeah yeah, just disabled all the plugins and new error:
Bot5 (957bd75a-2799-3660-aa34-d1833e9c00b3) has logged in
java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 1/2)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
        at com.github.puregero.minecraftstresstest.FriendlyByteBuf.readByte(FriendlyByteBuf.java:496)
        at com.github.puregero.minecraftstresstest.FriendlyByteBuf.readVarInt(FriendlyByteBuf.java:55)
        at com.github.puregero.minecraftstresstest.FriendlyByteBuf.readUtf(FriendlyByteBuf.java:117)
        at com.github.puregero.minecraftstresstest.FriendlyByteBuf.readUtf(FriendlyByteBuf.java:113)
        at com.github.puregero.minecraftstresstest.Bot.channelReadConfig(Bot.java:235)
        at com.github.puregero.minecraftstresstest.Bot.channelRead(Bot.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:842)
Bot5 has disconnected from petrionyx.com:26465

**Comment by akisha009** [comment]
its paper 1.20.2 server. I changed the version in source code for porotocol to 1.20.2

**Comment by akisha009** [comment]
Here is also log from console if you need it:
[12:11:30 INFO]: UUID of player Bot1 is 51a4b33d-8b80-3bde-806f-de4086b03058
[12:11:30 INFO]: UUID of player Bot2 is 16beaa94-ff1b-37a7-8afb-c22dcb8c16d1
[12:11:30 INFO]: com.mojang.authlib.GameProfile@79d4edc2[id=51a4b33d-8b80-3bde-806f-de4086b03058,name=Bot1,properties={}] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 4
[12:11:30 INFO]: UUID of player Bot3 is 73f370b4-497b-347a-a6bb-50d07eb88947
[12:11:30 INFO]: com.mojang.authlib.GameProfile@3fc18f98[id=16beaa94-ff1b-37a7-8afb-c22dcb8c16d1,name=Bot2,properties={}] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 4
[12:11:31 INFO]: UUID of player Bot4 is c760baae-cdc1-3595-98d0-c7a6e074d851
[12:11:31 INFO]: com.mojang.authlib.GameProfile@70eb5bbf[id=73f370b4-497b-347a-a6bb-50d07eb88947,name=Bot3,properties={}] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 4
[12:11:31 INFO]: UUID of player Bot5 is 957bd75a-2799-3660-aa34-d1833e9c00b3
[12:11:31 INFO]: com.mojang.authlib.GameProfile@10d73811[id=c760baae-cdc1-3595-98d0-c7a6e074d851,name=Bot4,properties={}] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 4
[12:11:31 INFO]: com.mojang.authlib.GameProfile@796626a8[id=957bd75a-2799-3660-aa34-d1833e9c00b3,name=Bot5,properties={}] lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: Index 10 out of bounds for length 4

**Comment by PureGero** [comment]
> I changed the version in source code for porotocol to 1.20.2

Unfortunately protocols don't work like that. Each protocol version is incompatible with one-another, so changing the protocol number doesn't magically make it compatible.

Install ViaVersion on your server to allow the 1.21 protocol bots to join the 1.20.2 server

**Comment by akisha009** [comment]
I fixed it! Thanks a lot!
